[package]
name = "aptbox"
version = "0.0.1"
authors = []

[addresses]
# Replace with your account address before publishing:
#   aptos move publish --named-addresses aptbox=<your_addr>
aptbox = "_"

[dev-addresses]
aptbox = "0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
